### ISSUE TITLE
Responsibility to free allocated memory?

### ISSUE THREAD

**Issue by canadaduane** [vmxdev/tkvdb#6]
I'm a little confused about whose responsibility it is to free dynamically allocated memory when `get` is used. As far as I understand, the `tkvdb_datum` struct has a `(void *)` pointer that can contain any length of value. Should this pointer be freed by calling code after a transaction? If not, how does it get freed?

See "Whose responsibility is it to free val.data?" comment in this sample code for clarification:

```
#include <stdio.h>
#include <string.h>
#include "../tkvdb/tkvdb.h"

int main(int argc, char const *argv[])
{
    const char *keyName = "name";
    const int values = 100;

    tkvdb *db = tkvdb_open("db.tkvdb", NULL);
    tkvdb_tr *transaction = tkvdb_tr_create(db, NULL);

    tkvdb_datum key;

    key.data = (void *)keyName;
    key.size = strlen(keyName);

    {
        tkvdb_datum val;

        transaction->begin(transaction);
        transaction->get(transaction, &key, &val);
        transaction->commit(transaction);

        // Whose responsibility is it to free val.data?
    }

    transaction->free(transaction);

    tkvdb_close(db);

    return 0;
}
```

Thanks!

**Comment by vmxdev** [comment]
After `get` val.data will point to memory somewhere in "transaction". In fact value is a part of tree node, located after node prefix (if any). You don't have to free it manually, it will be freed on `commit`, `rollback` or `transaction->free()`.

You may think of transactions as just memory buffer. After `get`, `put` or cursor operations it will contain nodes (and values) that was requested.

The following code
`
        transaction->begin(transaction);
        transaction->get(transaction, &key, &val);
        transaction->commit(transaction);
`
will append transaction with just one key-value pair (or root node + some nodes that was used for key search) to the DB file. After `commit` `val.data` pointer becomes invalid.
If you don't need to hold duplicate key-value pairs in database, you can `rollback` transactions after series of `get`'s

**Comment by canadaduane** [comment]
Thank you, this makes sense!

I may need one clarification:

> The following code ... transaction->get ... will append transaction with just one key-value pair (or root node + some nodes that was used for key search) to the DB file.

Do you mean for `transaction->put`? Why would a `get` append to the DB file? (maybe I'm missing something important).

**Comment by vmxdev** [comment]
It works in following manner:

`transaction->begin(transaction);` - starts transaction (resets to initial state)

`transaction->get(transaction, &key, &val);` - search for the key in "transaction". Since the transaction is now empty, function will load root node from DB file in it. If key can be found, function will load intermediate nodes and leaf node with data into "transaction" and returns pointer to value.
Here you can call more `get` or some cursor functions, they will load required nodes into transaction (keeping them unmodified). If you will call `put` function, all the affected nodes will be changed in memory.

`transaction->commit(transaction);` - here we just append all the transaction contents to DB file. Database now will have the new root node and some duplicate nodes for the "key".

The purpose of such a design is to keep hot (most recently accessed) nodes near the tail of database file to avoid long disk seeks.

If you don't need to keep duplicate nodes in database file, you can do reads with one transaction (calling `rollback` sometimes to limit transaction memory usage) and write with another transaction.

I guess misunderstanding occurs mostly because of bad naming: "transaction" here means mostly memory buffer with modified (or unmodified) nodes.

**Comment by canadaduane** [comment]
That's exactly what I needed. I'm toying with a Rust library to wrap tkvdb, but since I'm also concurrently learning Rust, we'll see how it goes ;) Thanks for your help.

**Comment by vmxdev** [comment]
>I'm toying with a Rust library to wrap tkvdb
It would be great if you will share your project

>Thanks for your help
You're welcome
